apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-service
  template:
    metadata:
      labels:
        app: board-service
    spec:
      containers:
        - name: board-service
          image: kevin0459/board-service:39f69ee57913644066d9d0a6d4b57f0dbf2a560b
          ports:
            - containerPort: 8001