apiVersion: v1
kind: Service
metadata:
  name: board-service
spec:
  selector:
    app: board-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
#      nodePort: 30080  # NodePort는 30000-32767 범위 내에서 선택합니다.