server:
  port: 0
spring:
  application:
    name: board-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100
  sql:
    init:
      mode: always
  profiles:
    active: local

