version: "3.8"
services:
  redis_container:
    image: redis:latest
    container_name: redis_container
    hostname: localhost
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    restart: always
    command: redis-server /usr/local/conf/redis.conf