server:
  port: 9001
spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_db
  kafka:
    consumer:
      auto-offset-reset: latest
      max-poll-records: 600000

logging:
  level:
    org.apache.kafka: ERROR
