apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: board-service
          image: kevin0459/chat-service:b34b35c7c6b26159814828ccf44ed5ebdfb1eeee
          ports:
            - containerPort: 8002