apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: board-service
          image: kevin0459/chat-service:6050ac3bc6a3a606df7bf854cd2935e69d319565
          ports:
            - containerPort: 8002